# This file was generated by GoReleaser. DO NOT EDIT.
cask "surge" do
  version "0.12.1"

  on_macos do
    on_arm do
      sha256 "954aa56b4e1776081e20f4d45ba7a6f1f90bfa5e4c5dad72e8814ed49da8b3ce"
      url "https://github.com/SurgeDM/Surge/releases/download/v#{version}/Surge_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8220c1cf978ef35c613cb564171e97aaa22b046efc94daa70137678fa9d4be65"
      url "https://github.com/SurgeDM/Surge/releases/download/v#{version}/Surge_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b177246288c0233ee27b69d78aeb58cc2cc8481b7cb842bf8e5f567c999deaf3"
      url "https://github.com/SurgeDM/Surge/releases/download/v#{version}/Surge_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "ff409af731c65bd9732fc209b2aa46245cbed425d41fa488e149f4d9a0dfbe38"
      url "https://github.com/SurgeDM/Surge/releases/download/v#{version}/Surge_#{version}_linux_amd64.tar.gz"
    end
  end

  name "surge"
  desc "Blazing fast TUI download manager built in Go for power users"
  homepage "https://github.com/SurgeDM/Surge"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "surge"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/surge"]
    end
  end

  # No zap stanza required
end
