# This file was generated by GoReleaser. DO NOT EDIT.
cask "surge" do
  version "0.12.0"

  on_macos do
    on_intel do
      sha256 "6aa4b06cca34494cd7dbdf4be51fc89e9d588867cd3444b95171c79935b4d1c4"
      url "https://github.com/SurgeDM/Surge/releases/download/v#{version}/Surge_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "68f231242117e9ecd136983ffff5549479319bd45742cfb575bb55a5324241c4"
      url "https://github.com/SurgeDM/Surge/releases/download/v#{version}/Surge_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "beb5f49b3b5349c61aea912616e15d7580d4785a833eec4104564d05105ddd8b"
      url "https://github.com/SurgeDM/Surge/releases/download/v#{version}/Surge_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "83951f1093366622e5835c6bcdc6cef73a200dbdc7d1ef53c42166c1f8b81974"
      url "https://github.com/SurgeDM/Surge/releases/download/v#{version}/Surge_#{version}_linux_arm64.tar.gz"
    end
  end

  name "surge"
  desc "Blazing fast TUI download manager built in Go for power users"
  homepage "https://github.com/SurgeDM/Surge"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "surge"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/surge"]
    end
  end

  # No zap stanza required

end
